# Generated by Django 2.2.4 on 2019-08-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.TextField(max_length=200)),
                ('main_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('name', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory')),
            ],
        ),
    ]
