# Generated by Django 2.2.4 on 2019-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190808_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
